apiVersion: v1
kind: Namespace
metadata:
  name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      initContainers:
      - name: go-build
        image: golang:1.21.0
        command: ["/bin/sh", "-c"]
        args:
        - git clone https://github.com/a2ush/sample-grpc-server-with-appmesh-xray.git && cd sample-grpc-server-with-appmesh-xray/grpc && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o grpc-server server/server.go && mv grpc-server /mnt/
        volumeMounts:
        - name: share-volume
          mountPath: /mnt
      containers:
      - name: server
        image: amazonlinux:2
        command: ["/mnt/grpc-server"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: share-volume
          mountPath: /mnt
      volumes:
      - name: share-volume
        emptyDir:
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: grpc  
spec:
  selector:
    app: grpc-server
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051