apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: server
        image: redis:7.2.4
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: grpc
spec:
  selector:
    app: redis-server
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379