apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: grpc-server-virtualnode
  namespace: grpc
spec:
  podSelector:
    matchLabels:
      app: grpc-server
  listeners:
    - portMapping:
        port: 50051
        protocol: grpc
  backends:
    - virtualService:
        virtualServiceRef:
          name: redis-server-virtualservice        
  serviceDiscovery:
    dns:
      hostname: grpc-server.grpc.svc.cluster.local
