apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  namespace: grpc
  name: grpc-server-virtualnode
spec:
  podSelector:
    matchLabels:
      app: grpc-server
  listeners:
    - portMapping:
        port: 50051
        protocol: grpc
  serviceDiscovery:
    dns:
      hostname: grpc-server.grpc.svc.cluster.local
